# Generated by Django 3.1.7 on 2021-03-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to='uploads/'),
        ),
    ]
